# Name of the container image.
image: doma2mo10/kamal-next-staging

proxy: 
  ssl: true
  host: stg.ksxqew.com
  # kamal-proxy connects to your container over port 80, use `app_port` to specify a different port.
  app_port: 3001
  healthcheck:
    interval: 3
    path: /api/up
    timeout: 3

# Configure builder setup.
builder:
  arch: amd64
  dockerfile: ./docker/staging/Dockerfile

env:
  secret:
    - BASIC_AUTH_DISABLED
    - BASIC_AUTH_USER
    - BASIC_AUTH_PASSWORD
