# Name of the container image.
image: doma2mo10/kamal-next

proxy: 
  ssl: true
  host: ksxqew.com
  app_port: 3000
  healthcheck:
    interval: 3
    path: /api/up
    timeout: 3

# Configure builder setup.
builder:
  arch: amd64
  dockerfile: ./docker/production/Dockerfile